application: quorastuff
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  expiration: "60d"
- url: /(.*.(jpg|svg|gif|png))
  static_files: static/images/\1
  upload: static/images/(.*.(jpg|svg|gif|png))
- url: /*.otf
  static_dir: css/fonts
  mime_type: application/font-sfnt
  expiration: "60d"
- url: /*.ttf
  static_dir: css/fonts
  mime_type: application/font-sfnt
  expiration: "60d"
- url: /*.css
  static_dir: css
  expiration: "60d"
- url: /*.js
  static_dir: js
- url: /.*
  script: quorastuff.application
  secure: optional

libraries:
- name: webapp2
  version: latest
